services:
  blue:
    build: .
    container_name: blue
    environment:
      - APP_POOL=blue
      - RELEASE_ID=1.0.1
    ports:
      - "8081:3000"

  green:
    build: .
    container_name: green
    environment:
      - APP_POOL=green
      - RELEASE_ID=1.0.0
    ports:
      - "8082:3000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - blue
      - green
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
