version: '3.8'

services:
  web:
    build: .
    container_name: devops_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: devops_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    depends_on:
      - web
